name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Tests (OTP ${{ matrix.otp }} | Elixir ${{ matrix.elixir }})
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: test

    strategy:
      matrix:
        include:
          - elixir: 1.17.3
            otp: 26.2.5.2
          - elixir: 1.18.4
            otp: 27.3
          - elixir: 1.18.4
            otp: 28.0.1

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: browser-actions/setup-chrome@v2.1.2
        id: setup-chrome
        with:
          chrome-version: stable
          install-dependencies: false
          install-chromedriver: true

      - name: Set up Elixir
        uses: erlef/setup-beam@3580539ceec3dc05b0ed51e9e10b08eb7a7c2bb4
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore Mix dependencies cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306
        with:
          path: |
            deps
            _build
          key: deps-soonex-i18n-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            deps-soonex-i18n-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Install Mix dependencies
        run: mix deps.get

      - name: Download Localize locale data
        run: mix localize.download_locales

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: assets/package-lock.json

      - name: Install npm dependencies
        working-directory: assets
        run: npm ci

      - name: Run tests
        env:
          WALLABY_CHROME_BINARY: ${{ steps.setup-chrome.outputs.chrome-path }}
          WALLABY_CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
        run: mix test --timeout 600000
